import { Container } from '@radix-ui/themes';
import '@radix-ui/themes/styles.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { cookies } from 'next/headers';
import Script from 'next/script';
import './globals.css';
import NavBar from './NavBar';
import ThemeProvider from './ThemeProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const cookieStore = cookies();
  const cookieTheme = cookieStore.get('theme')?.value;
  const initialTheme =
    cookieTheme === 'light' || cookieTheme === 'dark' ? cookieTheme : null;
  const htmlClassName = initialTheme === 'dark' ? 'dark' : undefined;

  return (
    <html
      lang='en'
      suppressHydrationWarning
      className={htmlClassName}
      style={initialTheme ? { colorScheme: initialTheme } : undefined}
    >
      <head>
        <Script id='theme-init' strategy='beforeInteractive'>
          {`(() => {
  try {
    const stored = localStorage.getItem('theme');
    const cookieMatch = document.cookie.match(/(?:^|; )theme=(dark|light)/);
    const cookieTheme = cookieMatch ? cookieMatch[1] : null;
    const prefersDark = window.matchMedia('(prefers-color-scheme: dark)').matches;
    const theme =
      stored === 'light' || stored === 'dark'
        ? stored
        : cookieTheme === 'light' || cookieTheme === 'dark'
          ? cookieTheme
          : prefersDark
            ? 'dark'
            : 'light';
    if (stored !== theme) {
      localStorage.setItem('theme', theme);
    }
    document.documentElement.classList.toggle('dark', theme === 'dark');
    document.documentElement.style.colorScheme = theme;
  } catch {}
})();`}
        </Script>
      </head>
      <body
        className={`${inter.className} min-h-screen bg-slate-50 text-slate-900 antialiased transition-colors duration-300 dark:bg-slate-950 dark:text-slate-100`}
      >
        <ThemeProvider>
          <NavBar />
          <Container>
            <main className='p-5'>{children}</main>
          </Container>
        </ThemeProvider>
      </body>
    </html>
  );
}
